name: Development CI

on:
  push:
    branches:
      - '**'  # Matches any branch
  pull_request:
    branches:
      - '**'

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  code-checks:
    uses: ./.github/workflows/code_quality_checks.yaml
